"""Evaluate the V20 hypotheses (VALIDATION_V20.md §3) mechanically.

    python validation/report_v20.py [--run v20_uea] [--out RESULTS_V20.md]

V20 is not a sweep and is not graded like one.  The claim is a *guarantee* --
never meaningfully worse than the best component -- so the unit is the cell, not
the mean, and a single violation anywhere falsifies it.  Averaging would hide
exactly the cell the claim is about.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from validation import margins as margins_lib

_spec = importlib.util.spec_from_file_location("run_validation", HERE / "run_validation.py")
run_validation = importlib.util.module_from_spec(_spec)
sys.modules["run_validation"] = run_validation
_spec.loader.exec_module(run_validation)

ARMS = run_validation.NO_REGRET_ARMS
TOLERANCE = 0.5   # points; the roadmap's bar


def per_seed(results, dataset, arm):
    return margins_lib.by_seed(results, dataset, f"heartwood_{arm}")


def regrets(results, dataset, arm):
    """Per-seed ``arm - best component``, in points. Negative is a regret."""
    components = [per_seed(results, dataset, c) for c in ARMS["components"]]
    model = per_seed(results, dataset, arm)
    seeds = sorted(set(model).intersection(*[set(c) for c in components]))
    return seeds, [100.0 * (model[s] - max(c[s] for c in components)) for s in seeds]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", default="v20_uea")
    parser.add_argument("--out", default="RESULTS_V20.md")
    args = parser.parse_args()

    results = margins_lib.load(args.run)
    datasets = sorted({r["dataset"] for r in results})

    out = [f"# V20 results — the no-regret guarantee ({args.run})", "",
           "Generated by `validation/report_v20.py`. The tolerance and the "
           "cell-level rule were frozen in `VALIDATION_V20.md` before any cell ran.", "",
           f"A **regret** is a cell scoring more than {TOLERANCE} points below the "
           "better of its two components (the ridge alone, the trees alone). The "
           "claim is a guarantee, so it is judged per cell: one violation "
           "falsifies it, and a mean would hide the cell the claim is about.", ""]

    out += ["## Worst cell per dataset", "",
            "| dataset | ridge alone | trees alone | unguarded | guarded | "
            "unguarded worst | guarded worst |", "|---" * 7 + "|"]

    violations = {"unguarded": [], "guarded": []}
    detail: dict[str, dict[str, list[float]]] = {"unguarded": {}, "guarded": {}}
    for dataset in datasets:
        cells = [f"| {dataset}"]
        for arm in (*ARMS["components"], ARMS["unguarded"], ARMS["guarded"]):
            cells.append(f"{margins_lib.mean_score(results, dataset, f'heartwood_{arm}'):.3f}")
        worst = {}
        for label in ("unguarded", "guarded"):
            seeds, values = regrets(results, dataset, ARMS[label])
            detail[label][dataset] = values
            worst[label] = min(values) if values else float("nan")
            for seed, value in zip(seeds, values):
                if value < -TOLERANCE:
                    violations[label].append((dataset, seed, value))
            cells.append(f"{worst[label]:+.1f}"
                         if worst[label] >= -TOLERANCE else f"**{worst[label]:+.1f}**")
        out.append(" | ".join(cells) + " |")
    out.append("")

    out += ["## Verdict", "",
            "| model | cells | violating cells | worst regret |", "|---|---|---|---|"]
    for label in ("unguarded", "guarded"):
        values = [v for series in detail[label].values() for v in series]
        worst = min(values) if values else float("nan")
        out.append(f"| {label} (`{ARMS[label]}`) | {len(values)} | "
                   f"{len(violations[label])} | {worst:+.1f} |")
    out.append("")

    passed = not violations["guarded"]
    out += [("**PASS — the guarantee holds.** No cell scores more than "
             f"{TOLERANCE} points below its best component."
             if passed else
             f"**FAIL — the guarantee does not hold.** {len(violations['guarded'])} "
             "cell(s) below tolerance:"), ""]
    if not passed:
        for dataset, seed, value in violations["guarded"]:
            out.append(f"* `{dataset}` seed {seed}: {value:+.1f}")
        out.append("")

    fixed = len(violations["unguarded"]) - len(violations["guarded"])
    out += ["## What the guarantee bought", "",
            f"The unguarded model violates the tolerance in "
            f"{len(violations['unguarded'])} cell(s); the guarded one in "
            f"{len(violations['guarded'])}. Net {fixed:+d}.", ""]
    if len(violations["unguarded"]) == 0:
        out += ["**No cell needed guarding in this suite.** The guarantee is "
                "untested here rather than confirmed: `VALIDATION_V20.md` §5 names "
                "this as the likeliest outcome and requires it to be reported as "
                "an absence of evidence, not as a pass.", ""]

    out += ["## Per-seed regrets", "",
            "Every cell, both models. Means are never reported without these.", ""]
    for label in ("unguarded", "guarded"):
        out += [f"**{label}**", ""]
        for dataset in datasets:
            values = detail[label].get(dataset) or []
            out.append(f"* `{dataset}`: "
                       + (", ".join(f"{v:+.1f}" for v in values) if values else "—"))
        out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
