"""Evaluate the V16 hypotheses (VALIDATION_V16.md §3) mechanically.

    python validation/report_v16.py [--run v16_uea] [--out RESULTS_V16.md]

The fractions under test come from ``BAGGING_ARMS`` in ``run_validation.py``, so
a fraction cannot be added to the study after its score is known -- which is the
specific way a "sweep the knob and report the best" study lies.  H-V16.1 is
therefore judged on **one fraction chosen the same way for every dataset**, not
on the per-dataset best; the per-dataset best is reported separately and
labelled as the optimistic number it is.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from validation import margins as margins_lib

_spec = importlib.util.spec_from_file_location("run_validation", HERE / "run_validation.py")
run_validation = importlib.util.module_from_spec(_spec)
sys.modules["run_validation"] = run_validation
_spec.loader.exec_module(run_validation)

BAGGING_ARMS = run_validation.BAGGING_ARMS
BASELINE = f"heartwood_{run_validation.BAGGING_BASELINE}"

BAR = 1.5        # H-V16.1, points -- roadmap item 2's bar
MAJORITY = 0.5


def margin(results, dataset, arm):
    return margins_lib.paired_margin(results, dataset, f"heartwood_{arm}", BASELINE)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", default="v16_uea")
    parser.add_argument("--out", default="RESULTS_V16.md")
    args = parser.parse_args()

    results = margins_lib.load(args.run)
    datasets = sorted({r["dataset"] for r in results})
    arms = list(BAGGING_ARMS)

    out = [f"# V16 results — per-node bagging against the winner's curse ({args.run})", "",
           "Generated by `validation/report_v16.py`. Fractions, bar and the "
           "single-fraction rule were frozen in `VALIDATION_V16.md` before any cell ran.", "",
           f"Metric: balanced accuracy. Margins are **points against `{BASELINE}`** "
           "(`candidate_colsample=1.0`), paired within seed.", ""]

    table: dict[str, dict[str, list[float]]] = {}
    notes: list[str] = []
    out += ["## Margins by bagging fraction", "",
            "| dataset | " + " | ".join(
                f"{arm} (×{BAGGING_ARMS[arm]:g})" for arm in arms) + " |",
            "|---" * (len(arms) + 1) + "|"]
    for d in datasets:
        cells = []
        for arm in arms:
            values, note = margin(results, d, arm)
            table.setdefault(arm, {})[d] = values
            if note:
                notes.append(f"* `{d}` / `{arm}`: {note}")
            if not values:
                cells.append("—")
            else:
                mean = float(np.mean(values))
                cells.append(f"**{mean:+.1f}**" if mean >= BAR else f"{mean:+.1f}")
        out.append(f"| {d} | " + " | ".join(cells) + " |")
    out.append("")
    if notes:
        out += ["**Incomplete cells** (reported, not averaged over):", "", *notes, ""]

    # ------------------------------------------------- H-V16.1, one fraction
    out += ["## H-V16.1 — one fraction, applied to every dataset", "",
            "| fraction | datasets clearing the bar | mean margin | verdict |",
            "|---|---|---|---|"]
    passing = []
    for arm in arms:
        per_dataset = {d: v for d, v in table[arm].items() if v}
        cleared = [d for d, v in per_dataset.items() if float(np.mean(v)) >= BAR]
        ok = bool(per_dataset) and len(cleared) > MAJORITY * len(per_dataset)
        overall = (float(np.mean([m for v in per_dataset.values() for m in v]))
                   if per_dataset else float("nan"))
        passing.append(ok)
        out.append(f"| ×{BAGGING_ARMS[arm]:g} | {len(cleared)} / {len(per_dataset)} | "
                   f"{overall:+.1f} | {'**PASS**' if ok else '**FAIL**'} |")
    out.append("")

    # -------------------------------------------- the optimistic number, labelled
    best_per_dataset = {}
    for d in datasets:
        options = {arm: float(np.mean(table[arm][d])) for arm in arms if table[arm].get(d)}
        if options:
            best_per_dataset[d] = max(options.items(), key=lambda kv: kv[1])
    out += ["## Per-dataset best fraction — **not** a result", "",
            "This is what the study would report if the fraction were chosen after "
            "seeing the score. It is here to be compared against the table above: "
            "the gap between them *is* the tuning optimism, and "
            "`validation/HEADROOM.md` is the record of what happens when that gap "
            "is mistaken for a gain.", "",
            "| dataset | best fraction | its margin |", "|---|---|---|"]
    for d, (arm, value) in sorted(best_per_dataset.items()):
        out.append(f"| {d} | ×{BAGGING_ARMS[arm]:g} | {value:+.1f} |")
    if best_per_dataset:
        cherry = float(np.mean([v for _, v in best_per_dataset.values()]))
        honest = max(
            (float(np.mean([m for v in table[arm].values() if v for m in v]))
             for arm in arms if any(table[arm].values())), default=float("nan"))
        out += ["", f"Cherry-picked mean **{cherry:+.1f}** against the best "
                    f"single-fraction mean **{honest:+.1f}** — a tuning optimism of "
                    f"**{cherry - honest:+.1f}** points.", ""]

    out += ["## Verdict", "",
            ("**PASS — bagging ships.** " if any(passing)
             else "**FAIL — bagging does not ship.** ")
            + ("At least one pre-named fraction clears +1.5 on a majority of datasets."
               if any(passing) else
               "No pre-named fraction clears +1.5 on a majority of datasets. Per "
               "`VALIDATION_V16.md` §4 the knob stays in the library at its "
               "no-op default and the roadmap moves to item 2b."), ""]

    out += ["## Per-seed margins", "",
            "Means above are never reported without these.", ""]
    for arm in arms:
        out.append(f"**{arm} (×{BAGGING_ARMS[arm]:g})**")
        out.append("")
        for d in datasets:
            v = table[arm].get(d) or []
            out.append(f"* `{d}`: " + (", ".join(f"{x:+.1f}" for x in v) if v else "—"))
        out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
