"""Evaluate the V15 hypotheses (VALIDATION_V15.md §3) mechanically.

    python validation/report_v15.py [--run v15_uea] [--out RESULTS_V15.md]

Which arm counts as "the +virtual-channels arm" comes from ``ABLATION_EXTRAS`` in
``run_validation.py``, not from anything here, so the mapping cannot be adjusted
after a score has been seen.  Every bar in §3 is applied by this script; nothing
is judged by eye.

Margins are paired within seed.  A dataset where an arm and the baseline did not
run the same seeds is reported as incomplete rather than averaged across
whatever happens to be present -- an unpaired mean is the kind of quiet defect
this project has already shipped twice.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent

_spec = importlib.util.spec_from_file_location("run_validation", HERE / "run_validation.py")
run_validation = importlib.util.module_from_spec(_spec)
sys.modules["run_validation"] = run_validation
_spec.loader.exec_module(run_validation)

ABLATION_EXTRAS = run_validation.ABLATION_EXTRAS
MULTICHANNEL_ONLY_EXTRAS = run_validation.MULTICHANNEL_ONLY_EXTRAS

METRIC = "balanced_accuracy"   # VALIDATION_V5.md headline
BAR = 0.5                      # H-V15.1..4, points
MAJORITY = 0.5                 # "a majority of datasets"
ADDITIVITY_SLACK = 1.0         # H-V15.5, points
BASELINE = "heartwood_abl_min"


def load(run: str) -> list[dict]:
    """Results for a run name under ``validation/rerun``, or an explicit path."""
    candidate = Path(run)
    path = candidate if candidate.is_dir() else HERE / "rerun" / run
    path = path / "results.json"
    if not path.exists():
        raise SystemExit(f"no results at {path} -- has the run finished?")
    return json.loads(path.read_text())["results"]


def by_seed(results, dataset: str, model: str) -> dict[int, float]:
    """Seed -> score, and a loud failure if a cell was somehow run twice."""
    out: dict[int, float] = {}
    for r in results:
        if r["dataset"] != dataset or r["model"] != model:
            continue
        if METRIC not in r["metrics"]:
            continue
        if r["seed"] in out:
            raise SystemExit(f"duplicate cell: {dataset} {model} seed {r['seed']}")
        out[r["seed"]] = r["metrics"][METRIC]
    return out


def paired_margin(results, dataset: str, arm: str) -> tuple[list[float], str]:
    """Per-seed ``arm - baseline`` in points, plus a note on what is missing."""
    base = by_seed(results, dataset, BASELINE)
    test = by_seed(results, dataset, f"heartwood_{arm}")
    shared = sorted(set(base) & set(test))
    dropped = sorted((set(base) | set(test)) - set(shared))
    note = "" if not dropped else f"unpaired seeds {dropped}"
    return [100.0 * (test[s] - base[s]) for s in shared], note


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", default="v15_uea")
    parser.add_argument("--out", default="RESULTS_V15.md")
    args = parser.parse_args()

    results = load(args.run)
    datasets = sorted({r["dataset"] for r in results})
    arms = ["abl_min", *ABLATION_EXTRAS.values(), "abl_all"]

    out = [f"# V15 results — what the bank's extras are worth ({args.run})", "",
           "Generated by `validation/report_v15.py`. Arms, bars and the majority rule "
           "were frozen in `VALIDATION_V15.md` before any cell was run.", "",
           f"Metric: balanced accuracy. Margins are **points against `{BASELINE}`**, "
           "paired within seed.", ""]

    # ------------------------------------------------------- absolute scores
    out += ["## Absolute scores", "",
            "| dataset | " + " | ".join(arms) + " | minirocket10k | agg |",
            "|---" * (len(arms) + 3) + "|"]
    for d in datasets:
        cells = []
        for arm in arms:
            v = list(by_seed(results, d, f"heartwood_{arm}").values())
            cells.append(f"{np.mean(v):.3f}" if v else "—")
        for extra in ("minirocket10k", "agg"):
            v = list(by_seed(results, d, extra).values())
            cells.append(f"{np.mean(v):.3f}" if v else "—")
        out.append(f"| {d} | " + " | ".join(cells) + " |")
    out.append("")

    # ------------------------------------------------------------- the bars
    out += ["## Margins over the MiniROCKET-only baseline", "",
            "Each cell is the mean paired margin in points; **bold** clears the "
            f"+{BAR} bar.", "",
            "| dataset | " + " | ".join(ABLATION_EXTRAS) + " | all |",
            "|---" * (len(ABLATION_EXTRAS) + 2) + "|"]

    margins: dict[str, dict[str, list[float]]] = {}
    notes: list[str] = []
    for d in datasets:
        cells = []
        for extra, arm in list(ABLATION_EXTRAS.items()) + [("all", "abl_all")]:
            values, note = paired_margin(results, d, arm)
            margins.setdefault(extra, {})[d] = values
            if note:
                notes.append(f"* `{d}` / `{arm}`: {note}")
            if not values:
                cells.append("—")
            else:
                mean = float(np.mean(values))
                cells.append(f"**{mean:+.1f}**" if mean >= BAR else f"{mean:+.1f}")
        out.append(f"| {d} | " + " | ".join(cells) + " |")
    out.append("")
    if notes:
        out += ["**Incomplete cells** (reported, not averaged over):", "", *notes, ""]

    # ------------------------------------------------------------- verdicts
    out += ["## Verdicts", "",
            "| hypothesis | extra | datasets clearing the bar | mean | verdict |",
            "|---|---|---|---|---|"]
    verdicts = {}
    for index, extra in enumerate(ABLATION_EXTRAS, start=1):
        per_dataset = margins.get(extra, {})
        live = {d: v for d, v in per_dataset.items() if v}
        cleared = [d for d, v in live.items() if float(np.mean(v)) >= BAR]
        passed = len(live) > 0 and len(cleared) > MAJORITY * len(live)
        verdicts[extra] = passed
        overall = float(np.mean([m for v in live.values() for m in v])) if live else float("nan")
        out.append(
            f"| H-V15.{index} | `{extra}` | {len(cleared)} / {len(live)} | "
            f"{overall:+.1f} | {'**PASS — survives**' if passed else '**FAIL — delete**'} |"
        )

    # H-V15.5: additivity
    all_margins = margins.get("all", {})
    additive = []
    for d in datasets:
        parts = [margins[e][d] for e in ABLATION_EXTRAS if margins.get(e, {}).get(d)]
        if not all_margins.get(d) or len(parts) != len(ABLATION_EXTRAS):
            continue
        predicted = sum(float(np.mean(p)) for p in parts)
        additive.append(float(np.mean(all_margins[d])) >= predicted - ADDITIVITY_SLACK)
    additivity = bool(additive) and sum(additive) > MAJORITY * len(additive)
    out.append(
        f"| H-V15.5 | additivity | {sum(additive)} / {len(additive)} | — | "
        f"{'**PASS**' if additivity else '**FAIL — one-at-a-time is inconclusive**'} |"
    )
    out.append("")

    # ------------------------------------------------ the §5 outcome check
    beats_all = [d for d in datasets
                 if all_margins.get(d) and float(np.mean(all_margins[d])) < 0]
    out += ["## Pre-registered checks", "",
            f"* Extras surviving §3: "
            f"{', '.join(f'`{e}`' for e, ok in verdicts.items() if ok) or '**none**'}.",
            f"* Extras to delete: "
            f"{', '.join(f'`{e}`' for e, ok in verdicts.items() if not ok) or 'none'}.",
            f"* `abl_min` beats `abl_all` on {len(beats_all)} / {len(datasets)} datasets"
            + (f" ({', '.join(beats_all)}) — see VALIDATION_V15.md §5." if beats_all else "."),
            "",
            "Extras marked PASS are **not established**: VALIDATION_V15.md §6 requires "
            "each to clear the same bar on PTB-XL (n=500, 5 seeds) before it ships.", ""]

    # ------------------------------------------------------- per-seed detail
    out += ["## Per-seed margins", "",
            "Means above are never reported without these (§7).", ""]
    for extra in list(ABLATION_EXTRAS) + ["all"]:
        out.append(f"**{extra}**")
        out.append("")
        for d in datasets:
            v = margins.get(extra, {}).get(d) or []
            out.append(f"* `{d}`: " + (", ".join(f"{x:+.1f}" for x in v) if v else "—"))
        out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
