"""Evaluate the V7 hypotheses (VALIDATION_V7.md §3) mechanically.

    python validation/report_v7.py

Stratified subsampling rounds a requested 1000 to 999 or 1001, so sizes are
bucketed to the nominal grid before anything is averaged -- otherwise one seed
lands in its own bucket and a three-seed mean silently becomes a one-seed mean.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROCKETS = ("minirocket", "minirocket10k")
WIN = 2.0            # points, VALIDATION_V7.md §3
STATIC_MIN = 1.0     # points D-C required by H-V7.3

DATASETS = {
    "cpsc2018": ("v7_cpsc", "v7_cpsc_nostatic", "v7_armb_cpsc2018"),
    "sleepedf": ("v7_sleepedf", "v7_sleepedf_nostatic", "v7_armb_sleepedf"),
}


def nominal(n: int) -> int:
    for target in (100, 250, 500, 1000, 2000):
        if abs(n - target) <= max(5, 0.05 * target):
            return target
    return n


def read(name: str) -> list[dict]:
    path = HERE / "rerun" / name / "results.json"
    if not path.exists():
        return []
    return json.loads(path.read_text())["results"]


def collect(key: str):
    main, nostatic, armb = DATASETS[key]
    cells: dict[int, dict[str, list[float]]] = defaultdict(lambda: defaultdict(list))
    for row in read(main):
        cells[nominal(row["n_train"])][row["model"]].append(
            row["metrics"]["balanced_accuracy"])
    for row in read(nostatic):
        cells[nominal(row["n_train"])]["armC"].append(row["metrics"]["balanced_accuracy"])
    for row in read(armb):
        cells[nominal(row["n_train"])]["armB"].append(row["metrics"]["balanced_accuracy"])
    return cells


def rocket(scores) -> float:
    """MiniROCKET credited with its better kernel budget."""
    return max(np.mean(scores[r]) for r in ROCKETS if r in scores)


def main() -> int:
    lines = ["# V7 results", "",
             "Generated by `validation/report_v7.py`. Hypotheses and thresholds were "
             "frozen in `VALIDATION_V7.md` before either dataset was fetched.", ""]
    verdicts = {}

    for key in DATASETS:
        cells = collect(key)
        if not cells:
            lines += [f"## {key} — not run", ""]
            continue
        lines += [f"## {key}", "",
                  "| n | heartwood+rocket | MiniROCKET | agg | static_only | vs rocket | seeds |",
                  "|---|---|---|---|---|---|---|"]
        margins = {}
        for size in sorted(cells):
            s = cells[size]
            if "heartwood_rocket" not in s:
                continue
            hw, rk = np.mean(s["heartwood_rocket"]), rocket(s)
            margins[size] = 100 * (hw - rk)
            static = np.mean(s["static_only"]) if s.get("static_only") else float("nan")
            lines.append(f"| {size} | {hw:.3f} | {rk:.3f} | {np.mean(s['agg']):.3f} | "
                         f"{static:.3f} | **{margins[size]:+.1f}** | "
                         f"{len(s['heartwood_rocket'])} |")
        verdicts[key] = margins

        # H-V7.3 decomposition, where the arms exist
        for size in sorted(cells):
            s = cells[size]
            if "armB" in s and "armC" in s and "heartwood_rocket" in s:
                A, B = rocket(s), np.mean(s["armB"])
                C, D = np.mean(s["armC"]), np.mean(s["heartwood_rocket"])
                lines += ["", f"**Decomposition at n={size}** — "
                          f"A aeon {A:.3f} | B our bank {B:.3f} | C +trees {C:.3f} | "
                          f"D +statics {D:.3f}", "",
                          f"* bank quality  B−A = **{100*(B-A):+.1f}**",
                          f"* trees add     C−B = **{100*(C-B):+.1f}**",
                          f"* statics add   D−C = **{100*(D-C):+.1f}**"]
        lines.append("")

    lines += ["## Verdicts", ""]
    ready = {k: v for k, v in verdicts.items() if 1000 in v and 2000 in v}
    if ready:
        failed = [k for k, v in ready.items() if v[1000] < WIN or v[2000] < WIN]
        h1 = "FAIL" if len(failed) > len(ready) / 2 else "PASS"
        lines.append(f"**H-V7.1 (replication)** — {h1} on {len(ready)} dataset(s). "
                     f"Needs >={WIN:.0f}pt at n=1000 and n=2000.")
        for k, v in ready.items():
            ok = "both" if v[1000] >= WIN and v[2000] >= WIN else "not both"
            lines.append(f"  {k}: n=1000 {v[1000]:+.1f}, n=2000 {v[2000]:+.1f} — {ok}")

        lines.append(f"**H-V7.2 (size dependence)** — needs the largest size to beat the "
                     f"smallest by >={WIN:.0f}pt.")
        for k, v in verdicts.items():
            if len(v) >= 2:
                lo, hi = min(v), max(v)
                delta = v[hi] - v[lo]
                lines.append(f"  {k}: n={lo} {v[lo]:+.1f} -> n={hi} {v[hi]:+.1f} = "
                             f"{delta:+.1f}pt — {'PASS' if delta >= WIN else 'FAIL'}")
    else:
        lines.append("Not enough completed cells to adjudicate; run still in progress.")

    # H-V7.3: what the statics are actually worth, adjudicated rather than eyeballed
    parts = []
    for key in DATASETS:
        cells = collect(key)
        for size in sorted(cells):
            s_ = cells[size]
            if "armB" in s_ and "armC" in s_ and "heartwood_rocket" in s_:
                C, D = np.mean(s_["armC"]), np.mean(s_["heartwood_rocket"])
                parts.append((key, size, 100 * (D - C)))
    if parts:
        harmed = [p for p in parts if p[2] < 0]
        h3 = ("FAIL (statics hurt)" if harmed
              else "PASS" if all(p[2] >= STATIC_MIN for p in parts) else "MARGINAL")
        lines.append(f"**H-V7.3 (mechanism)** — {h3}. Needs D-C >= {STATIC_MIN:.0f}pt; "
                     f"fails if the static block *hurts*.")
        for key, size, delta in parts:
            lines.append(f"  {key}@{size}: statics add {delta:+.1f}pt")

    report = "\n".join(lines)
    print(report)
    (HERE / "RESULTS_V7.md").write_text(report + "\n")
    print(f"\nwrote {HERE / 'RESULTS_V7.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
