"""Evaluate the V24 release gate (VALIDATION_V24.md §3) mechanically.

    python validation/report_v24.py [--out RESULTS_V24.md]

Three questions, and the library does not ship unless the answers are the ones
§4 requires: does it still beat MiniROCKET across sixteen UEA datasets, does the
single-lead CPSC headline survive, and did four separately-negligible deletions
compound into something that is not negligible.

The third is checked against ``abl_min`` cells recorded in V15 -- the same
datasets and seeds, measured on the bank the library now *is*.  Those numbers
exist already and cannot be re-run to taste.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from validation import margins as margins_lib

MODEL = "heartwood_rocket_static"
BASELINE = "minirocket10k"
UEA_MAJORITY = 9        # H-V24.1, of 16
CPSC_BAR = 2.0          # H-V24.2, points
COMPOUND_TOL = 1.0      # H-V24.3, points


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="RESULTS_V24.md")
    args = parser.parse_args()

    out = ["# V24 — the release gate", "",
           "Generated by `validation/report_v24.py`. Bars were frozen in "
           "`VALIDATION_V24.md` before any cell ran.", "",
           "**Every number here was measured on the code being released**, not on "
           "the version that produced the older headlines. That is the whole "
           "point of this document.", ""]

    # ---------------------------------------------------------- H-V24.1
    try:
        uea = margins_lib.load("v24_uea")
    except SystemExit:
        uea = None
    ahead = total = 0
    ours_all, theirs_all = [], []
    if uea is None:
        out += ["## H-V24.1 — breadth", "", "**NOT RUN.**", ""]
        h1 = None
    else:
        datasets = sorted({r["dataset"] for r in uea})
        out += ["## H-V24.1 — sixteen UEA datasets", "",
                "| dataset | heartwood | MiniROCKET-10k | MiniROCKET-2k | margin |",
                "|---|---|---|---|---|"]
        for d in datasets:
            ours = margins_lib.by_seed(uea, d, MODEL)
            theirs = margins_lib.by_seed(uea, d, BASELINE)
            small = margins_lib.by_seed(uea, d, "minirocket")
            shared = sorted(set(ours) & set(theirs))
            if not shared:
                out.append(f"| {d} | — | — | — | — |")
                continue
            a = float(np.mean([ours[s] for s in shared]))
            b = float(np.mean([theirs[s] for s in shared]))
            c = float(np.mean(list(small.values()))) if small else float("nan")
            margin = 100.0 * (a - b)
            total += 1
            ahead += margin > 0
            ours_all.append(a); theirs_all.append(b)
            mark = f"**{margin:+.1f}**" if margin > 0 else f"{margin:+.1f}"
            out.append(f"| {d} | {a:.3f} | {b:.3f} | {c:.3f} | {mark} |")
        mean_ours = float(np.mean(ours_all)) if ours_all else float("nan")
        mean_theirs = float(np.mean(theirs_all)) if theirs_all else float("nan")
        h1 = ahead >= UEA_MAJORITY and mean_ours >= mean_theirs
        out += ["", f"Mean balanced accuracy **{mean_ours:.3f}** against "
                    f"**{mean_theirs:.3f}**; ahead on **{ahead} of {total}** "
                    f"(bar: {UEA_MAJORITY}).",
                "", f"**H-V24.1 {'PASS' if h1 else 'FAIL'}**", ""]

    # ---------------------------------------------------------- H-V24.2
    try:
        cpsc = margins_lib.load("v24_cpsc")
    except SystemExit:
        cpsc = None
    if cpsc is None:
        out += ["## H-V24.2 — the headline", "", "**NOT RUN.**", ""]
        h2 = None
    else:
        ours = margins_lib.by_seed(cpsc, "cpsc2018", MODEL)
        theirs = margins_lib.by_seed(cpsc, "cpsc2018", BASELINE)
        shared = sorted(set(ours) & set(theirs))
        per_seed = [100.0 * (ours[s] - theirs[s]) for s in shared]
        margin = float(np.mean(per_seed)) if per_seed else float("nan")
        h2 = margin >= CPSC_BAR
        out += ["## H-V24.2 — CPSC-2018, single lead", "",
                f"| heartwood | MiniROCKET-10k | margin | bar | verdict |",
                "|---|---|---|---|---|",
                f"| {np.mean([ours[s] for s in shared]):.3f} | "
                f"{np.mean([theirs[s] for s in shared]):.3f} | **{margin:+.1f}** | "
                f"+{CPSC_BAR} | {'**PASS**' if h2 else '**FAIL**'} |", "",
                "Per seed: " + ", ".join(f"{v:+.1f}" for v in per_seed), "",
                f"The old library, with four extras since deleted, measured "
                f"**+3.0** here (`RESULTS_V14.md`, arm C).", ""]

    # ---------------------------------------------------------- H-V24.3
    out += ["## H-V24.3 — did the deletions compound?", "",
            "Against `abl_min` in V15: the same datasets and seeds, and that arm "
            "was MiniROCKET's plain bank under our trees, which is what the "
            "library now is. Those cells were recorded before any deletion.", ""]
    try:
        v15 = margins_lib.load("v15_uea")
    except SystemExit:
        v15 = None
    h3 = None
    if uea is not None and v15 is not None:
        out += ["| dataset | V15 `abl_min` | now | change |", "|---|---|---|---|"]
        worst, changes = 0.0, []
        for d in sorted({r["dataset"] for r in v15}):
            before = margins_lib.by_seed(v15, d, "heartwood_abl_min")
            after = margins_lib.by_seed(uea, d, MODEL)
            if not before or not after:
                continue
            a = 100.0 * float(np.mean(list(before.values())))
            b = 100.0 * float(np.mean(list(after.values())))
            changes.append(b - a)
            worst = min(worst, b - a)
            mark = f"{b - a:+.1f}" if b - a >= -COMPOUND_TOL else f"**{b - a:+.1f}**"
            out.append(f"| {d} | {a:.1f} | {b:.1f} | {mark} |")
        h3 = worst >= -COMPOUND_TOL
        out += ["", f"Worst change **{worst:+.1f}** points, mean "
                    f"{float(np.mean(changes)):+.1f} (tolerance −{COMPOUND_TOL}).",
                "", f"**H-V24.3 {'PASS' if h3 else 'FAIL'}**", ""]

    # ---------------------------------------------------------- verdict
    # The decision rule is §4's, not a blanket pass/fail: it distinguishes a
    # dead claim from a narrower one, and it was written before any cell ran.
    out += ["## Release verdict", ""]
    if None in (h1, h2, h3):
        out += ["**Incomplete — not cleared to release.**"]
    elif not h3:
        out += ["**NOT CLEARED — H-V24.3 failed.** Deletions compounded into "
                "damage no per-extra bar could see. Per §4 the release stops and "
                "the guilty extra is restored."]
    elif h1 and h2:
        out += ["**CLEARED — the general claim holds.** All three bars pass on the "
                "code being released."]
    elif h2:
        out += ["**CLEARED FOR A NARROWER CLAIM.** §4, written before any cell "
                "ran: *\"the library is a CPSC/ECG result rather than a general "
                "time-series result, and the README says so. That is a narrower "
                "claim, not a dead one.\"*", "",
                "So the honest statement is: **strong on ECG, and behind "
                "MiniROCKET on most general time-series benchmarks.** The README "
                "carries both halves of that, and the second half is not a "
                "footnote.", "",
                "Note the two summaries of H-V24.1 disagree and both are "
                "reported. Mean balanced accuracy favours this library; the "
                "count of datasets favours MiniROCKET. A single 22-point win on "
                "EthanolConcentration carries the mean, which is exactly the kind "
                "of thing a mean hides and a count does not."]
    else:
        out += ["**NOT CLEARED — the headline did not survive.** Per §4 the claim "
                "is withdrawn; there is no re-running until it passes."]
    out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
