"""Evaluate the V25 hypotheses (VALIDATION_V25.md §3) mechanically.

    python validation/report_v25.py [--out RESULTS_V25.md]

The control (H-V25.1) is evaluated and printed first: the ``ridge`` head is the
same pipeline as V24's ``minirocket10k``, so if it does not reproduce it the two
studies are not comparable and nothing else here means anything.

Heads are ranked by **mean rank across datasets** as well as by mean score,
because eight candidates make the best-of-eight optimistically biased and because
a mean can be carried by one large margin where a rank cannot.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from validation import margins as margins_lib

HEADS = ["ridge", "logreg", "linsvc", "hgb", "rf", "extratrees", "knn", "mlp"]
CONTROL_TOL = 0.5      # H-V25.1, points
BAR = 1.0              # H-V25.2 / H-V25.3, points
MAJORITY = 9           # of 16
HEARTWOOD = "heartwood_rocket_static"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="RESULTS_V25.md")
    args = parser.parse_args()

    v25 = margins_lib.load("v25_uea")
    v24 = margins_lib.load("v24_uea")
    datasets = sorted({r["dataset"] for r in v25})

    def head(h, d):
        v = list(margins_lib.by_seed(v25, d, f"bank_{h}").values())
        return 100.0 * float(np.mean(v)) if v else float("nan")

    def hw(d):
        v = list(margins_lib.by_seed(v24, d, HEARTWOOD).values())
        return 100.0 * float(np.mean(v)) if v else float("nan")

    out = ["# V25 — what belongs on top of the bank?", "",
           "Generated by `validation/report_v25.py`. Heads, bars and the "
           "one-head-everywhere rule were frozen in `VALIDATION_V25.md` before "
           "any cell ran.", "",
           "Every arm shares the identical MiniROCKET transform; only the final "
           "estimator differs. Balanced accuracy, official splits, 5 seeds — the "
           "same cells as `RESULTS_V24.md`.", ""]

    # ------------------------------------------------------ H-V25.1, control
    worst = max(abs(head("ridge", d) - 100.0 * float(np.mean(
        list(margins_lib.by_seed(v24, d, "minirocket10k").values()))))
        for d in datasets)
    ok = worst <= CONTROL_TOL
    out += ["## H-V25.1 — the control", "",
            "The `ridge` head is the same pipeline as V24's `minirocket10k`, so "
            "it must reproduce it. Checked first: if it fails, nothing below is "
            "interpretable.", "",
            f"Largest discrepancy across all {len(datasets)} datasets: "
            f"**{worst:.2f} points** (tolerance {CONTROL_TOL}).", "",
            f"**H-V25.1 {'PASS' if ok else 'FAIL'}**"
            + (" — the protocols are identical, so V24's Heartwood column is "
               "directly comparable and needed no re-running." if ok else
               " — the studies are not comparable; stop here."), ""]
    if not ok:
        Path(args.out).write_text("\n".join(out)); print("\n".join(out)); return 0

    # ------------------------------------------------------------- standings
    everyone = {h: {d: head(h, d) for d in datasets} for h in HEADS}
    everyone["heartwood"] = {d: hw(d) for d in datasets}
    ranks = {k: [] for k in everyone}
    for d in datasets:
        for i, k in enumerate(sorted(everyone, key=lambda k: -everyone[k][d]), 1):
            ranks[k].append(i)

    out += ["## Standings", "",
            "`heartwood` is not a head on this bank — it also draws interval, "
            "shapelet and filter candidates and can split on statics — so it is "
            "an architecture in the table rather than a competitor for the same "
            "slot. Its numbers are V24's, unchanged.", "",
            "| model | mean | mean rank | vs ridge | beats ridge by ≥1 | beats "
            "heartwood by ≥1 |", "|---|---|---|---|---|---|"]
    table = []
    for k in list(HEADS) + ["heartwood"]:
        mean = float(np.mean([everyone[k][d] for d in datasets]))
        mrank = float(np.mean(ranks[k]))
        vs = float(np.mean([everyone[k][d] - everyone["ridge"][d] for d in datasets]))
        br = sum(everyone[k][d] >= everyone["ridge"][d] + BAR for d in datasets)
        bh = sum(everyone[k][d] >= everyone["heartwood"][d] + BAR for d in datasets)
        table.append((mrank, k, mean, vs, br, bh))
    for mrank, k, mean, vs, br, bh in sorted(table):
        name = f"**{k}**" if k in ("ridge", "heartwood") else k
        out.append(f"| {name} | {mean:.1f} | {mrank:.2f} | {vs:+.1f} | "
                   f"{br}/{len(datasets)} | {bh}/{len(datasets)} |")
    out.append("")

    # -------------------------------------------------------- H-V25.2, H-V25.3
    best_vs_ridge = max((v for v in table if v[1] != "ridge"), key=lambda v: v[4])
    best_vs_hw = max((v for v in table if v[1] != "heartwood"), key=lambda v: v[5])
    h2 = best_vs_ridge[4] >= MAJORITY
    h3 = best_vs_hw[5] >= MAJORITY
    out += ["## Verdicts", "",
            "| hypothesis | question | best challenger | verdict |",
            "|---|---|---|---|",
            f"| H-V25.2 | is the ridge the right head? | `{best_vs_ridge[1]}`, "
            f"{best_vs_ridge[4]}/{len(datasets)} (bar {MAJORITY}) | "
            f"{'**FAIL — nothing beats the ridge**' if not h2 else '**PASS**'} |",
            f"| H-V25.3 | are the trees the right head? | `{best_vs_hw[1]}`, "
            f"{best_vs_hw[5]}/{len(datasets)} (bar {MAJORITY}) | "
            f"{'**FAIL — nothing beats Heartwood either**' if not h3 else '**PASS**'} |",
            ""]

    # ------------------------------------------------- the mean/rank disagreement
    diffs = {d: everyone["heartwood"][d] - everyone["ridge"][d] for d in datasets}
    biggest = max(diffs, key=diffs.get)
    without = float(np.mean([v for d, v in diffs.items() if d != biggest]))
    out += ["## The mean disagrees with the rank, again", "",
            f"Heartwood has the **highest mean** ({np.mean([everyone['heartwood'][d] for d in datasets]):.1f}) "
            f"and the **third-best rank** ({np.mean(ranks['heartwood']):.2f}). Those "
            "cannot both be the headline.", "",
            f"Its mean advantage over the ridge is **{np.mean(list(diffs.values())):+.1f}** "
            f"points. Excluding `{biggest}` alone — where it wins by "
            f"{diffs[biggest]:+.1f} — that becomes **{without:+.1f}**.", "",
            "So one dataset carries the whole advantage. `RESULTS_V24.md` "
            "flagged the same pattern; this quantifies it. **The rank is the "
            "honest summary.**", ""]

    # -------------------------------------------------------- what it means
    linear = [t for t in sorted(table) if t[1] in ("ridge", "logreg", "linsvc")]
    out += ["## What this means", "",
            "**A linear shrinkage estimator is the right head, and MiniROCKET "
            "chose correctly.** The two best-ranked models on this bank are both "
            "linear, and *every* nonlinear head — random forest, extremely "
            "randomised trees, histogram boosting, k-NN, an MLP — ranks below "
            "them. The bank's value is in its features; what sits on top should "
            "mostly get out of the way.", "",
            "**The scouting note in `validation/DATALETS.md` was half right and "
            "is corrected here.** It observed that a tournament beat a plain "
            "histogram booster and speculated *\\\"the answer might not be "
            "trees\\\"*. The answer is indeed not trees — but not because "
            "something more elaborate wins. It is because something *simpler* "
            "does.", "",
            "**Heartwood is competitive, not dominant.** Nothing beat it by the "
            "bar, and it beat nothing by the bar. On rank it sits third, behind "
            "two linear heads; on mean it leads, on the strength of one dataset. "
            "That is consistent with `RESULTS_V24.md` and neither better nor "
            "worse than it.", "",
            f"**The outcome §5 named as least welcome did not occur.** A stock "
            f"histogram booster ranks {dict((t[1], t[0]) for t in table)['hgb']:.2f}, "
            f"{dict((t[1], t[3]) for t in table)['hgb']:+.1f} points against the "
            "ridge — far from beating it or Heartwood. The temporal machinery is "
            "not worse than doing nothing special.", ""]

    out += ["## Per-dataset scores", "",
            "| dataset | " + " | ".join(HEADS) + " | heartwood |",
            "|---" * (len(HEADS) + 2) + "|"]
    for d in datasets:
        cells = [f"{everyone[h][d]:.1f}" for h in HEADS]
        out.append(f"| {d} | " + " | ".join(cells)
                   + f" | {everyone['heartwood'][d]:.1f} |")
    out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
