"""Evaluate the V23 hypotheses (VALIDATION_V23.md §4) mechanically.

    python validation/report_v23.py [--out RESULTS_V23.md]

Reads two runs: the held-out UEA suite (H-V23.1, H-V23.2) and the synthetic
scenarios (H-V23.3, the positive control).  The control is reported in the same
document and never counted toward the bars -- it exists to say whether a null on
the real suite is interpretable, not to argue for the extras.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from validation import margins as margins_lib

_spec = importlib.util.spec_from_file_location("run_validation", HERE / "run_validation.py")
run_validation = importlib.util.module_from_spec(_spec)
sys.modules["run_validation"] = run_validation
_spec.loader.exec_module(run_validation)

EXTRAS = run_validation.V23_EXTRAS
BASELINE = f"heartwood_{run_validation.V23_BASELINE}"
BAR = 0.5          # H-V23.1/2, same as V15 by design
MAJORITY = 0.5
CONTROL_BAR = 5.0  # H-V23.3, points
#: Which scenario each extra was built for, named in VALIDATION_V23.md §4.
CONTROL = {"comparison_splits": ("bump_order", "hw_v23_cmp"),
           "levy_areas": ("lead_lag", "hw_v23_levy")}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", default="v23_uea")
    parser.add_argument("--control", default="v23_synth")
    parser.add_argument("--out", default="RESULTS_V23.md")
    args = parser.parse_args()

    results = margins_lib.load(args.run)
    datasets = sorted({r["dataset"] for r in results})

    out = ["# V23 results — do comparison splits and Lévy areas work anywhere real?", "",
           "Generated by `validation/report_v23.py`. Suite rule, arms and bars were "
           "frozen in `VALIDATION_V23.md` before any cell ran.", "",
           f"Metric: balanced accuracy. Margins are points against `{BASELINE}` "
           "(both extras off), paired within seed.", ""]

    # ------------------------------------------------- H-V23.3 first: is this readable?
    out += ["## H-V23.3 — can this study detect the effects at all?", "",
            "The same arms on the scenarios each extra was built for. **Not evidence "
            "for the extras** — those scenarios were written to require these "
            "operators — but evidence about whether a null below is interpretable.", "",
            "| extra | scenario | baseline | with extra | gain | verdict |",
            "|---|---|---|---|---|---|"]
    control_ok = True
    control_path = HERE / "rerun" / args.control / "results.json"
    if not control_path.exists():
        out += ["| — | — | — | — | — | **NOT RUN** |", "",
                "**The control did not run, so H-V23.1 and H-V23.2 below are "
                "uninterpretable.**", ""]
        control_ok = False
    else:
        payload = json.loads(control_path.read_text())
        rows = payload["results"] if isinstance(payload, dict) else payload
        for extra, (scenario, arm) in CONTROL.items():
            def mean_of(model):
                vals = [r["metrics"]["roc_auc"] for r in rows
                        if r.get("scenario") == scenario and r.get("model") == model
                        and "roc_auc" in r.get("metrics", {})]
                return 100.0 * float(np.mean(vals)) if vals else float("nan")
            base, with_extra = mean_of("hw_v23_base"), mean_of(arm)
            gain = with_extra - base
            ok = gain >= CONTROL_BAR
            control_ok &= bool(ok)
            out.append(f"| `{extra}` | {scenario} | {base:.1f} | {with_extra:.1f} | "
                       f"**{gain:+.1f}** | {'**PASS**' if ok else '**FAIL**'} |")
        out += ["", ("**The study can detect these effects.** A null on the real suite "
                     "below therefore means something." if control_ok else
                     "**The control failed. H-V23.1 and H-V23.2 are reported but "
                     "must not be read as evidence** — per §5 the arms are debugged "
                     "before anything is concluded."), ""]

    # ---------------------------------------------------- the real suite
    out += ["## Margins on the held-out UEA suite", "",
            "| dataset | " + " | ".join(f"`{e}`" for e in EXTRAS) + " | both |",
            "|---" * (len(EXTRAS) + 2) + "|"]
    table, notes = {}, []
    for dataset in datasets:
        cells = []
        for extra, arm in list(EXTRAS.items()) + [("both", "v23_both")]:
            values, note = margins_lib.paired_margin(
                results, dataset, f"heartwood_{arm}", BASELINE)
            table.setdefault(extra, {})[dataset] = values
            if note:
                notes.append(f"* `{dataset}` / `{arm}`: {note}")
            if not values:
                cells.append("—")
            else:
                mean = float(np.mean(values))
                cells.append(f"**{mean:+.1f}**" if mean >= BAR else f"{mean:+.1f}")
        out.append(f"| {dataset} | " + " | ".join(cells) + " |")
    out.append("")
    if notes:
        out += ["**Incomplete cells:**", "", *notes, ""]

    out += ["## Verdicts", "",
            "| hypothesis | extra | datasets clearing +0.5 | mean | verdict |",
            "|---|---|---|---|---|"]
    verdicts = {}
    for index, extra in enumerate(EXTRAS, start=1):
        live = {d: v for d, v in table[extra].items() if v}
        cleared = [d for d, v in live.items() if float(np.mean(v)) >= BAR]
        passed = bool(live) and len(cleared) > MAJORITY * len(live)
        verdicts[extra] = passed
        overall = (float(np.mean([m for v in live.values() for m in v]))
                   if live else float("nan"))
        out.append(f"| H-V23.{index} | `{extra}` | {len(cleared)} / {len(live)} | "
                   f"{overall:+.1f} | {'**PASS**' if passed else '**FAIL**'} |")
    out.append("")

    out += ["## What this means", ""]
    if not control_ok:
        out += ["The control failed, so nothing above is interpretable (§5)."]
    elif not any(verdicts.values()):
        out += ["**Both extras fail on a second independent real suite.**", "",
                "Sixteen real datasets across V15 and V23, no effect on either, "
                "against two synthetic scenarios written to require exactly these "
                "operators — and the control above confirms the study would have "
                "seen an effect if one were there.", "",
                "Per `VALIDATION_V23.md` §5 the honest reading is that **both "
                "features work only on tasks constructed to need them, and should "
                "be deleted** — completing what `VALIDATION_V15.md` §4 instructed "
                "and this project declined to do on one suite's evidence. The "
                "synthetic wins stay in the record as what they are: proof the "
                "operators function, not proof they are worth carrying."]
    else:
        survivors = ", ".join(f"`{e}`" for e, ok in verdicts.items() if ok)
        out += [f"**{survivors} clears the bar on a suite chosen by a rule fixed "
                "before any score.** V15's verdict is suite-specific rather than "
                "wrong. §6 requires a mean well clear of zero, not a bare "
                "five-of-eight — check the per-seed vectors below before shipping."]
    out.append("")

    out += ["## Per-seed margins", "",
            "Means are never reported without these.", ""]
    for extra in list(EXTRAS) + ["both"]:
        out += [f"**{extra}**", ""]
        for dataset in datasets:
            values = table.get(extra, {}).get(dataset) or []
            out.append(f"* `{dataset}`: "
                       + (", ".join(f"{x:+.1f}" for x in values) if values else "—"))
        out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
