"""Evaluate the V14 hypotheses (VALIDATION_V14.md §3) mechanically.

    python validation/report_v14.py [--out RESULTS_V14.md]

V14 asks whether channel width causes this library's margin over MiniROCKET, by
holding the dataset, task, split, seed and label fixed and varying only the
number of ECG leads.  The three arms live in separate output directories because
they were separate invocations, so this is the one report here that reads more
than one run.

Every bar in §3 is applied here, including the per-seed sign-consistency clause
of H-V14.1 -- which is the part most easily lost if a mean is eyeballed instead.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from validation import margins as margins_lib

DATASET = "cpsc2018"
MODEL = "heartwood_rocket_static"
#: Arm -> (run directory, lead count), in the order VALIDATION_V14.md names them.
ARMS = {
    "A": ("v14_cpsc_ch12", 12),
    "B": ("v14_cpsc_ch3", 3),
    "C": ("v14_cpsc_ch1", 1),
}
#: The baseline each arm is measured against, fitted on the *same* restricted
#: series so it degrades with width exactly as we do.
BASELINES = ("minirocket10k", "minirocket")

WIDTH_BAR = 3.0        # H-V14.1, points
SIGN_SEEDS = 4         # H-V14.1, of 5


def arm_margins(arm: str, baseline: str, root: Path) -> tuple[dict[int, float], str]:
    """Seed -> (heartwood - baseline) in points, for one arm."""
    run, _leads = ARMS[arm]
    path = root / run
    if not (path / "results.json").exists():
        return {}, f"arm {arm}: no results at {path}"
    results = margins_lib.load(str(path))
    ours = margins_lib.by_seed(results, DATASET, MODEL)
    theirs = margins_lib.by_seed(results, DATASET, baseline)
    shared = sorted(set(ours) & set(theirs))
    missing = sorted((set(ours) | set(theirs)) - set(shared))
    note = "" if not missing else f"arm {arm}: unpaired seeds {missing}"
    return {s: 100.0 * (ours[s] - theirs[s]) for s in shared}, note


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="RESULTS_V14.md")
    parser.add_argument("--baseline", default=BASELINES[0], choices=BASELINES)
    parser.add_argument("--root", type=Path, default=HERE / "rerun",
                        help="directory holding the per-arm run directories")
    args = parser.parse_args()

    per_arm, notes = {}, []
    for arm in ARMS:
        values, note = arm_margins(arm, args.baseline, args.root)
        per_arm[arm] = values
        if note:
            notes.append(f"* {note}")

    ready = [arm for arm in ARMS if per_arm[arm]]
    out = ["# V14 results — does channel width cause the MiniROCKET margin?", "",
           "Generated by `validation/report_v14.py`. Arms, bars and the "
           "sign-consistency rule were frozen in `VALIDATION_V14.md` before any "
           "cell was run.", "",
           f"Metric: balanced accuracy. Margins are **points against "
           f"`{args.baseline}` fitted on the same restricted leads**, paired "
           "within seed.", ""]

    if len(ready) < len(ARMS):
        out += [f"**INCOMPLETE — {len(ready)} of {len(ARMS)} arms have results.** "
                "Reported as incomplete rather than judged on what finished; "
                "`VALIDATION_V14.md` §6 says a cell that fails to run is "
                "reported as failed, not omitted.", ""]

    out += ["## Margins by arm", "",
            "| arm | leads | per-seed margin | mean |", "|---|---|---|---|"]
    for arm, (_run, leads) in ARMS.items():
        values = per_arm[arm]
        if not values:
            out.append(f"| {arm} | {leads} | — | — |")
            continue
        vector = ", ".join(f"{v:+.1f}" for v in values.values())
        out.append(f"| {arm} | {leads} | {vector} | **{np.mean(list(values.values())):+.1f}** |")
    out.append("")
    if notes:
        out += ["**Incomplete cells:**", "", *notes, ""]

    def mean(arm):
        return float(np.mean(list(per_arm[arm].values()))) if per_arm[arm] else float("nan")

    out += ["## Hypotheses", "", "| hypothesis | claim | result | verdict |",
            "|---|---|---|---|"]

    # H-V14.1 -- width causes the margin.
    if per_arm["A"] and per_arm["C"]:
        gap = mean("A") - mean("C")
        shared = sorted(set(per_arm["A"]) & set(per_arm["C"]))
        agreeing = sum(1 for s in shared
                       if np.sign(per_arm["A"][s] - per_arm["C"][s]) == np.sign(gap))
        passed = gap >= WIDTH_BAR and agreeing >= SIGN_SEEDS
        out.append(
            f"| H-V14.1 | width causes it | margin(A)−margin(C) = **{gap:+.1f}** "
            f"(bar {WIDTH_BAR:+.1f}), sign agrees on {agreeing}/{len(shared)} seeds "
            f"(bar {SIGN_SEEDS}) | {'**PASS**' if passed else '**FAIL**'} |")
    else:
        passed = None
        out.append("| H-V14.1 | width causes it | arms A and C not both complete | — |")

    # H-V14.2 -- dose response.
    if all(per_arm[a] for a in ARMS):
        ordered = mean("A") >= mean("B") >= mean("C")
        out.append(
            f"| H-V14.2 | dose response | {mean('A'):+.1f} ≥ {mean('B'):+.1f} ≥ "
            f"{mean('C'):+.1f} | {'**PASS**' if ordered else '**FAIL**'} |")
    else:
        out.append("| H-V14.2 | dose response | not all arms complete | — |")

    # H-V14.3 -- the control.
    if per_arm["C"]:
        survives = mean("C") > 0
        out.append(
            f"| H-V14.3 | margin survives at one lead | margin(C) = "
            f"**{mean('C'):+.1f}** | {'**PASS**' if survives else '**FAIL**'} |")
    else:
        survives = None
        out.append("| H-V14.3 | margin survives at one lead | arm C not complete | — |")
    out.append("")

    # ------------------------------------------------ what it means, per §4
    out += ["## What this means", ""]
    if passed is None or survives is None:
        out.append("Withheld until every arm has run.")
    elif passed:
        out += ["**Width is the mechanism.** Per `VALIDATION_V14.md` §4 the next work "
                "is making the bank degrade gracefully on narrow input — the "
                "cross-channel features should cost nothing when there is nothing to "
                "cross — and the library gets an honest scope statement: strongest on "
                "multi-channel series."]
    elif survives:
        out += ["**Width is not the mechanism, and the V13 write-up needs correcting a "
                "second time.** The margin survives at one lead, so Apnea's loss is "
                "about Apnea rather than about channel count.", "",
                "`VALIDATION_V14.md` §5 named this as the outcome it would least like: "
                "a mechanism was published in `RESULTS_V13.md` and in the README on the "
                "strength of a correlation across four confounded datasets, with a "
                "counterexample — single-channel Sleep-EDF, which we win — already "
                "sitting in the results directory. This document exists so that outcome "
                "is recorded rather than quietly dropped.", "",
                "The dataset screen offers a competing explanation with no channels in "
                "it: Apnea's regime gap is −0.010, so a global summary of that "
                "one-minute ECG loses nothing a finer representation recovers "
                "(`RESULTS_SCREEN.md`). Roadmap item 8 is the README correction."]
    else:
        out += ["**We lose at one lead too, but by less than the bar demands.** Width "
                "matters weakly and something else matters as well "
                "(`VALIDATION_V14.md` §4)."]
    out.append("")

    out += ["## Absolute scores", "",
            "| arm | leads | heartwood | minirocket10k | minirocket 2k | agg |",
            "|---|---|---|---|---|---|"]
    for arm, (run, leads) in ARMS.items():
        if not per_arm[arm]:
            out.append(f"| {arm} | {leads} | — | — | — | — |")
            continue
        results = margins_lib.load(str(args.root / run))
        cells = [f"{margins_lib.mean_score(results, DATASET, m):.3f}"
                 for m in (MODEL, "minirocket10k", "minirocket", "agg")]
        out.append(f"| {arm} | {leads} | " + " | ".join(cells) + " |")
    out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
