"""Evaluate the V22 hypotheses (VALIDATION_V22.md §3) mechanically.

    python validation/report_v22.py [--out RESULTS_V22.md]

V22 is graded differently from the sweep studies, and deliberately.  H-V22.2 is a
**veto**: V11 collapsed on Apnea-ECG to 0.478 AUC, below chance, and did it
silently, so no product change ships if any arm falls more than 2 points below
the baseline there -- whatever the diagnostic says.  The veto is therefore read
first and printed first.

Two runs are read: the synthetic generators (H-V22.1, H-V22.3) and the Apnea
grid (H-V22.2).  A missing run is reported, never treated as a pass.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from validation import margins as margins_lib

BASELINE = "rocket_static"
ARMS = ("prod_split", "prod_margin", "prod_both")

DIAGNOSTIC = "amp_regression"
IMPROVE_BAR = 4.0        # H-V22.1, % RMSE reduction
ORACLE_CEILING = 8.4     # measured in VALIDATION_V22.md §2, for context only
VETO_POINTS = 2.0        # H-V22.2, AUC points
REGRESS_RMSE = 2.0       # H-V22.3, % RMSE
REGRESS_POINTS = 1.0     # H-V22.3, points


def synthetic(root: Path):
    path = root / "v22_synth" / "results.json"
    if not path.exists():
        return None
    payload = json.loads(path.read_text())
    return payload["results"] if isinstance(payload, dict) else payload


def by_seed(rows, scenario, model, metric):
    out = {}
    for r in rows:
        if r.get("scenario") == scenario and r.get("model") == model:
            value = r.get("metrics", {}).get(metric)
            if value is not None:
                out[r["seed"]] = value
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="RESULTS_V22.md")
    parser.add_argument("--root", type=Path, default=HERE / "rerun")
    args = parser.parse_args()

    out = ["# V22 results — magnitude products", "",
           "Generated by `validation/report_v22.py`. Bars were frozen in "
           "`VALIDATION_V22.md` before any benchmark cell was run.", ""]

    # ------------------------------------------------ H-V22.2, the veto, first
    out += ["## H-V22.2 — the Apnea veto", "",
            "Read first because it is a veto, not a contribution. V11 fell to "
            "0.478 AUC here, below chance, and did it silently.", ""]
    apnea_path = args.root / "v22_apnea" / "results.json"
    veto_failures, veto_known = [], False
    if not apnea_path.exists():
        out += ["**NOT RUN.** No arm may ship until it is. Reported as missing, "
                "not as a pass.", ""]
    else:
        veto_known = True
        results = margins_lib.load(str(args.root / "v22_apnea"))
        out += ["| arm | AUC | margin vs baseline | verdict |", "|---|---|---|---|"]
        base = margins_lib.by_seed(results, "apnea", f"heartwood_{BASELINE}", "roc_auc")
        out.append(f"| `{BASELINE}` (baseline) | {np.mean(list(base.values())):.3f} | — | — |")
        for arm in ARMS:
            arm_scores = margins_lib.by_seed(results, "apnea", f"heartwood_{arm}", "roc_auc")
            shared = sorted(set(base) & set(arm_scores))
            margin = 100.0 * float(np.mean([arm_scores[s] - base[s] for s in shared]))
            ok = margin >= -VETO_POINTS
            if not ok:
                veto_failures.append(arm)
            out.append(f"| `{arm}` | {np.mean([arm_scores[s] for s in shared]):.3f} | "
                       f"**{margin:+.1f}** | {'ok' if ok else '**VETOED**'} |")
        out += ["", ("**PASS — no arm collapses on Apnea.** The argument in "
                     "`VALIDATION_V22.md` §2 holds: these products feed trees, and a "
                     "tree returns a leaf value however large its input, so V11's "
                     "linear extrapolation failure has no route here."
                     if not veto_failures else
                     f"**FAIL — vetoed: {', '.join(veto_failures)}.** §4 says the "
                     "tree-cannot-extrapolate argument is then wrong and gets "
                     "corrected before anything else is attempted."), ""]

    rows = synthetic(args.root)
    if rows is None:
        out += ["## H-V22.1 and H-V22.3", "", "**NOT RUN.**", ""]
        Path(args.out).write_text("\n".join(out))
        print("\n".join(out))
        return 0

    # ------------------------------------------------ H-V22.1, the diagnostic
    base = by_seed(rows, DIAGNOSTIC, f"hw_{BASELINE}", "rmse")
    out += ["## H-V22.1 — does the diagnostic improve?", "",
            f"`{DIAGNOSTIC}`, 5 seeds, RMSE. Bar is a **{IMPROVE_BAR:.0f}%** "
            f"reduction — set below the **{ORACLE_CEILING:.1f}%** an oracle product "
            "column reaches (§2), because a bar above a measured ceiling is "
            "unpassable and a bar at it is a demand for luck.", "",
            "| arm | RMSE | reduction | verdict |", "|---|---|---|---|",
            f"| `{BASELINE}` | {np.mean(list(base.values())):.4f} | — | — |"]
    best, improved = None, False
    for arm in ARMS:
        arm_scores = by_seed(rows, DIAGNOSTIC, f"hw_{arm}", "rmse")
        shared = sorted(set(base) & set(arm_scores))
        mean = float(np.mean([arm_scores[s] for s in shared]))
        cut = 100.0 * (np.mean([base[s] for s in shared]) - mean) / np.mean(
            [base[s] for s in shared])
        ok = cut >= IMPROVE_BAR
        improved |= ok
        if best is None or cut > best[1]:
            best = (arm, cut)
        out.append(f"| `{arm}` | {mean:.4f} | **{cut:+.1f}%** | "
                   f"{'**PASS**' if ok else 'below bar'} |")
    out += ["", f"**{'PASS' if improved else 'FAIL'}** — best arm `{best[0]}` at "
                f"{best[1]:+.1f}% against a {IMPROVE_BAR:.0f}% bar "
                f"({100 * best[1] / ORACLE_CEILING:.0f}% of the oracle ceiling).", ""]

    # ------------------------------------------------ H-V22.3, no regression
    scenarios = sorted({r.get("scenario") for r in rows})
    out += ["## H-V22.3 — does anything else regress?", "",
            f"No scenario worse than baseline by more than {REGRESS_RMSE:.0f}% RMSE "
            f"or {REGRESS_POINTS:.0f} point. `{DIAGNOSTIC}` is one of "
            f"{len(scenarios)} and a fix that costs the others is not a fix.", "",
            "| scenario | metric | " + " | ".join(f"`{a}`" for a in ARMS) + " |",
            "|---" * (len(ARMS) + 2) + "|"]
    regressions = []
    skipped = []
    for scenario in scenarios:
        # Regression scenarios carry rmse; the binary ones carry roc_auc and no
        # r2 at all. The first version of this looked for rmse then r2, found
        # neither on four of the five scenarios, skipped them in silence and
        # printed PASS on the strength of one -- a no-regression check that
        # checked almost nothing and said so nowhere.
        for metric in ("rmse", "roc_auc"):
            ref = by_seed(rows, scenario, f"hw_{BASELINE}", metric)
            if ref:
                break
        if not ref:
            skipped.append(scenario)
            continue
        cells = []
        for arm in ARMS:
            arm_scores = by_seed(rows, scenario, f"hw_{arm}", metric)
            shared = sorted(set(ref) & set(arm_scores))
            if not shared:
                cells.append("—")
                continue
            a = float(np.mean([arm_scores[s] for s in shared]))
            b = float(np.mean([ref[s] for s in shared]))
            if metric == "rmse":
                change = 100.0 * (b - a) / b        # positive = better
                bad = change < -REGRESS_RMSE
                cells.append(f"{change:+.1f}%" if not bad else f"**{change:+.1f}%**")
            else:
                change = 100.0 * (a - b)
                bad = change < -REGRESS_POINTS
                cells.append(f"{change:+.1f}" if not bad else f"**{change:+.1f}**")
            if bad:
                regressions.append(f"{scenario}/{arm}")
        out.append(f"| {scenario} | {metric} | " + " | ".join(cells) + " |")
    if skipped:
        out += ["", f"**Scenarios with no comparable metric: {', '.join(skipped)}.** "
                    "Reported, never silently dropped -- a no-regression check is "
                    "worth exactly the scenarios it actually covered."]
    out += ["", ("**PASS — nothing regresses beyond tolerance.**" if not regressions
                 else f"**FAIL — {len(regressions)} regression(s): "
                      f"{', '.join(regressions)}.**")
            + f" Covered {len(scenarios) - len(skipped)} of {len(scenarios)} scenarios.",
            ""]

    # ------------------------------------------------------------- what it means
    out += ["## Verdict", ""]
    if veto_known and veto_failures:
        out += ["**Does not ship.** The Apnea veto fired."]
    elif not improved:
        out += ["**Does not ship.** The diagnostic did not clear its bar, so two "
                "routes to a magnitude product both fell short under a measured "
                f"{ORACLE_CEILING:.1f}% ceiling.", "",
                "Per `VALIDATION_V22.md` §4 that says the operands are still wrong "
                "rather than the currency — most likely the bank holds no clean "
                "amplitude carrier for the signal window at all, which is a "
                "statement about the *bank* and sends this back to item 1 rather "
                "than forward.", "",
                "`VALIDATION_V22.md` §5 named a `prod_margin`-only win as the "
                "outcome it would least like, because that arm multiplies the "
                "base's margin by a static the margin already contains. Worth "
                "checking against the table above before drawing any conclusion "
                "about the mechanism."]
    else:
        out += ["**Ships**, subject to the veto above: the diagnostic clears its "
                "bar, nothing else regresses, and Apnea holds."]
    out.append("")

    text = "\n".join(out)
    Path(args.out).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
