"""Evaluate the V5 hypotheses (VALIDATION_V5.md §4) mechanically.

    python validation/report_v5.py validation/rerun/ptbxl validation/rerun/ueaB

The point of doing it in code is the same as in ``report.py``: the verdict should
not depend on which numbers anyone chooses to look at.  Thresholds are read from
the pre-registration and are not arguments.

V5 is evaluated **only** on datasets v0.3 never touched, because every hypothesis
here was generated by looking at corrected v0.3 results.  Passing v0.3 paths in
would be testing a hypothesis on the data that suggested it.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

from report import headline_for, load  # same package directory

#: VALIDATION_V5.md §2 -- computed from baselines only, never from Heartwood.
SHAPE_REGIME = 5.0
SUMMARY_REGIME = 2.0
WIN_MARGIN = 2.0

#: The rank set for H-V5.2.  MiniROCKET is one competitor credited with its
#: better kernel budget, not two.
BASELINES = ("agg", "wagg4", "wagg8", "raw_flat", "minirocket")
ROCKETS = ("minirocket", "minirocket10k")

#: Datasets v0.3 used; present only so passing them in fails loudly.
V0_3 = {"credit", "har", "icu", "uea:StandWalkJump", "uea:AtrialFibrillation",
        "uea:ERing", "uea:BasicMotions", "uea:UWaveGestureLibrary",
        "uea:Cricket", "uea:DuckDuckGeese", "uea:EigenWorms"}


def cells(rows: list[dict]) -> dict[tuple[str, int], dict[str, float]]:
    """(dataset, n_train) -> {model: mean headline over seeds}."""
    buckets: dict[tuple[str, int, str], list[float]] = defaultdict(list)
    for row in rows:
        value = row["metrics"].get(headline_for(row["dataset"]))
        if value is not None and np.isfinite(value):
            buckets[(row["dataset"], row["n_train"], row["model"])].append(value)
    out: dict[tuple[str, int], dict[str, float]] = defaultdict(dict)
    for (dataset, size, model), values in buckets.items():
        out[(dataset, size)][model] = float(np.mean(values))
    return dict(out)


def regime(scores: dict[str, float]) -> tuple[str, float]:
    """Classify a cell using baselines only (VALIDATION_V5.md §2)."""
    if "agg" not in scores:
        return "unclassified", float("nan")
    rivals = [v for k, v in scores.items() if k in BASELINES + ROCKETS and k != "agg"]
    if not rivals:
        return "unclassified", float("nan")
    loss = 100 * (max(rivals) - scores["agg"])
    if loss >= SHAPE_REGIME:
        return "shape", loss
    if loss <= SUMMARY_REGIME:
        return "summary", loss
    return "ambiguous", loss


def rank_of(scores: dict[str, float]) -> dict[str, int]:
    """Competition rank, 1 = best, over heartwood plus one entry per baseline."""
    entries = {"heartwood": scores["heartwood"]}
    for name in BASELINES:
        if name == "minirocket":
            rockets = [scores[r] for r in ROCKETS if r in scores]
            if rockets:
                entries["minirocket"] = max(rockets)  # credited with its better budget
        elif name in scores:
            entries[name] = scores[name]
    order = sorted(entries, key=lambda k: -entries[k])
    return {name: index + 1 for index, name in enumerate(order)}


def main() -> int:
    paths = [Path(p) for p in sys.argv[1:]]
    if not paths:
        print("usage: report_v5.py <results dir> [...]")
        return 1
    table = cells(load(paths))

    used = {key[0] for key in table}
    if overlap := used & V0_3:
        print(f"REFUSING: {sorted(overlap)} were used in v0.3 and suggested these "
              "hypotheses; V5 is evaluated only on datasets v0.3 never touched.")
        return 1

    lines = ["# V5 results", "",
             "Generated by `validation/report_v5.py`. Hypotheses and thresholds were "
             "frozen in `VALIDATION_V5.md` before any V5 dataset was fetched.", "",
             "## Cells, regime, and rank", "",
             "`aggregation_loss` is the best non-`agg` baseline minus `agg`, in points. "
             "It uses no Heartwood run, so the regime cannot be fitted to the answer.", "",
             "| dataset | n | regime | agg_loss | heartwood | agg | best rocket | "
             "hw − agg | hw rank |",
             "|---|---|---|---|---|---|---|---|---|"]

    shape_cells, summary_cells, ranks = [], [], defaultdict(list)
    for key in sorted(table):
        scores = table[key]
        if "heartwood" not in scores:
            continue
        label, loss = regime(scores)
        margin = 100 * (scores["heartwood"] - scores["agg"]) if "agg" in scores else float("nan")
        rocket = max([scores[r] for r in ROCKETS if r in scores], default=float("nan"))
        rank = rank_of(scores)
        for model, value in rank.items():
            ranks[model].append(value)
        if label == "shape":
            shape_cells.append((key, margin))
        elif label == "summary":
            summary_cells.append((key, margin))
        lines.append(
            f"| {key[0]} | {key[1]} | {label} | {loss:+.1f} | {scores['heartwood']:.3f} | "
            f"{scores.get('agg', float('nan')):.3f} | {rocket:.3f} | {margin:+.1f} | "
            f"{rank['heartwood']} |"
        )

    lines += ["", "## Verdicts", ""]

    # ---- H-V5.1
    wins = sum(1 for _, m in shape_cells if m >= WIN_MARGIN)
    shape_rate = wins / len(shape_cells) if shape_cells else float("nan")
    harmed = sum(1 for _, m in summary_cells if m < -WIN_MARGIN)
    safe_rate = 1 - harmed / len(summary_cells) if summary_cells else float("nan")
    helps = shape_rate >= 0.60
    harms = (shape_rate < 0.50) or (summary_cells and harmed / len(summary_cells) > 0.20)
    h1 = "FAIL" if harms else ("PASS" if helps and (not summary_cells or safe_rate >= 0.80)
                               else "INCONCLUSIVE")
    lines.append(
        f"**H-V5.1 (conditional core claim)** — {h1}. Shape regime: beat `agg` by "
        f">={WIN_MARGIN:.0f}pt on {wins}/{len(shape_cells)} cells "
        f"({shape_rate:.0%}; pass >=60%, fail <50%). Summary regime: within "
        f"{WIN_MARGIN:.0f}pt of `agg` on {len(summary_cells) - harmed}/{len(summary_cells)} "
        f"cells ({safe_rate:.0%}; pass >=80%)."
    )
    for name, group in (("shape", shape_cells), ("summary", summary_cells)):
        if group:
            lines.append(f"  {name}: " + ", ".join(
                f"{d.replace('uea:', '')}@{n} {m:+.1f}" for (d, n), m in group))

    # ---- H-V5.2
    mean_rank = {m: float(np.mean(v)) for m, v in ranks.items() if v}
    hw = mean_rank.get("heartwood", float("nan"))
    beaten = [m for m, r in mean_rank.items() if m != "heartwood" and r <= hw]
    h2 = "FAIL" if beaten else "PASS"
    lines.append(
        f"**H-V5.2 (regime robustness)** — {h2}. Mean rank over "
        f"{len(ranks['heartwood'])} cells: "
        + ", ".join(f"{m} {r:.2f}" for m, r in sorted(mean_rank.items(), key=lambda x: x[1]))
        + (f". Beaten or tied by: {', '.join(beaten)}." if beaten else
           ". Strictly better than every individual baseline.")
    )

    # ---- H-V5.3, Arm A only (the mixed dataset with a real static block)
    arm_a = [k for k in table if "static_only" in table[k]]
    if arm_a:
        both = 0
        detail = []
        for key in sorted(arm_a):
            scores = table[key]
            rocket = max([scores[r] for r in ROCKETS if r in scores], default=None)
            over_agg = 100 * (scores["heartwood"] - scores["agg"])
            over_rocket = (100 * (scores["heartwood"] - rocket)
                           if rocket is not None else float("nan"))
            both += int(over_agg >= WIN_MARGIN and over_rocket >= WIN_MARGIN)
            detail.append(f"{key[0]}@{key[1]} agg{over_agg:+.1f} rocket{over_rocket:+.1f}")
        h3 = "PASS" if both > len(arm_a) / 2 else "FAIL"
        lines.append(
            f"**H-V5.3 (the empty cell)** — {h3}. Beat both `agg` and the better "
            f"MiniROCKET by >={WIN_MARGIN:.0f}pt on {both}/{len(arm_a)} sizes; pass needs "
            f"a majority.")
        lines.append("  " + "; ".join(detail))
        # precondition
        for key in sorted(arm_a):
            scores = table[key]
            lines.append(
                f"  precondition {key[0]}@{key[1]}: static_only={scores['static_only']:.3f}"
            )

    report = "\n".join(lines)
    print(report)
    out = Path(__file__).parent / "RESULTS_V5.md"
    out.write_text(report + "\n")
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    raise SystemExit(main())
