"""Evaluate the V10 hypotheses (VALIDATION_V10.md §3) mechanically.

    python validation/report_v10.py

Reports every metric, not just the pre-registered headline. Precision, recall
and F1 were named as pain points in the original brief and `VALIDATION.md` §5
promised them alongside; a result that appears only in the headline metric is one
worth distrusting.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
METRICS = ("roc_auc", "accuracy", "balanced_accuracy", "precision", "recall", "f1")
WIN = 2.0          # H-V10.1, points
STATIC_GAIN = 4.0  # H-V10.2, points


def rows(name: str) -> list[dict]:
    path = HERE / "rerun" / name / "results.json"
    return json.loads(path.read_text())["results"] if path.exists() else []


def series(name: str, model: str, metric: str) -> list[float]:
    return [r["metrics"][metric] for r in rows(name)
            if r["model"] == model and metric in r["metrics"]]


def main() -> int:
    out = ["# V10 results — the base sees the static block", "",
           "Generated by `validation/report_v10.py`. Hypotheses and thresholds were frozen "
           "in `VALIDATION_V10.md` before the change was implemented.", ""]

    full, blind = "v10_apnea", "v10_apnea_nostatic"
    model = "heartwood_rocket_static"

    out += ["## Apnea-ECG, n=1000, 5 seeds — every metric", "",
            "| model | " + " | ".join(METRICS) + " |",
            "|---" * (len(METRICS) + 1) + "|"]
    labels = {model: "**heartwood (V10)**", "static_only": "statics only",
              "agg": "aggregates", "minirocket": "MiniROCKET 2k",
              "minirocket10k": "MiniROCKET 10k"}
    for key, label in labels.items():
        values = [series(full, key, m) for m in METRICS]
        if not values[0]:
            continue
        out.append(f"| {label} | " + " | ".join(
            f"{np.mean(v):.3f}" if v else "—" for v in values) + " |")

    no_static = series(blind, model, "roc_auc")
    if no_static:
        out.append(f"| heartwood, statics removed | " + " | ".join(
            f"{np.mean(series(blind, model, m)):.3f}" if series(blind, model, m) else "—"
            for m in METRICS) + " |")

    D = series(full, model, "roc_auc")
    S = series(full, "static_only", "roc_auc")
    C = no_static
    out += ["", "## Verdicts", ""]

    paired = [100 * (d - s) for d, s in zip(D, S)]
    verdict = "PASS" if np.mean(paired) >= WIN else (
        "FAIL" if np.mean(paired) <= 0 else "MARGINAL")
    out.append(
        f"**H-V10.1 (the combination beats its best half)** — {verdict}. "
        f"AUC {np.mean(D):.3f} against `static_only` {np.mean(S):.3f}, "
        f"**{np.mean(paired):+.1f} points**; the bar was +{WIN:.0f}. "
        f"Per seed: {', '.join(f'{p:+.1f}' for p in paired)}.")

    if C:
        n = min(len(D), len(C))
        gain = [100 * (D[i] - C[i]) for i in range(n)]
        verdict2 = "PASS" if np.mean(gain) >= STATIC_GAIN else (
            "FAIL" if np.mean(gain) < 2.0 else "MARGINAL")
        out.append(
            f"**H-V10.2 (the statics contribute)** — {verdict2}. "
            f"Removing the static block costs **{np.mean(gain):+.1f} points** over "
            f"{n} shared seeds, against +2.0 when the statics could only reach the "
            f"model through tree splits. The bar was +{STATIC_GAIN:.0f}.")

    report = "\n".join(out)
    print(report)
    (HERE / "RESULTS_V10.md").write_text(report + "\n")
    print(f"\nwrote {HERE / 'RESULTS_V10.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
