"""Report a knob swept over pre-named values, with the tuning optimism printed.

V16 (per-node bagging) and V17 (the multiple-comparisons charge) are the same
study shape: one baseline, three values of one knob named before any cell ran,
and a bar the knob must clear.  That shape has a specific way of lying -- pick
the best value per dataset, average the winners, report a gain -- and
``validation/HEADROOM.md`` is this project's record of being fooled by it once.

So the rule is enforced here rather than remembered: a verdict is only ever
computed from **one value applied to every dataset**.  The per-dataset best is
still computed, because hiding it would be its own kind of dishonesty, but it is
labelled as not a result and the gap between the two is printed as the tuning
optimism it measures.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from validation import margins as margins_lib

MAJORITY = 0.5


def render(*, results, title, run, arms, baseline, bar, knob_label,
           value_format, baseline_note, fail_note) -> str:
    """Markdown for one swept-knob study.  ``arms`` maps arm name -> knob value."""
    datasets = sorted({r["dataset"] for r in results})
    names = list(arms)

    def label(arm):
        return f"{arm} ({value_format.format(arms[arm])})"

    out = [f"# {title} ({run})", "",
           f"Generated by `validation/sweep_report.py`. The {knob_label} values, the "
           f"+{bar} bar and the one-value-for-every-dataset rule were frozen before "
           "any cell ran.", "",
           f"Metric: balanced accuracy. Margins are **points against `{baseline}`** "
           f"({baseline_note}), paired within seed.", ""]

    table: dict[str, dict[str, list[float]]] = {}
    notes: list[str] = []
    out += [f"## Margins by {knob_label}", "",
            "| dataset | " + " | ".join(label(a) for a in names) + " |",
            "|---" * (len(names) + 1) + "|"]
    for dataset in datasets:
        cells = []
        for arm in names:
            values, note = margins_lib.paired_margin(
                results, dataset, f"heartwood_{arm}", baseline)
            table.setdefault(arm, {})[dataset] = values
            if note:
                notes.append(f"* `{dataset}` / `{arm}`: {note}")
            if not values:
                cells.append("—")
            else:
                mean = float(np.mean(values))
                cells.append(f"**{mean:+.1f}**" if mean >= bar else f"{mean:+.1f}")
        out.append(f"| {dataset} | " + " | ".join(cells) + " |")
    out.append("")
    if notes:
        out += ["**Incomplete cells** (reported, not averaged over):", "", *notes, ""]

    out += [f"## The bar — one {knob_label}, applied to every dataset", "",
            f"| {knob_label} | datasets clearing the bar | mean margin | verdict |",
            "|---|---|---|---|"]
    passing = []
    for arm in names:
        live = {d: v for d, v in table[arm].items() if v}
        cleared = [d for d, v in live.items() if float(np.mean(v)) >= bar]
        ok = bool(live) and len(cleared) > MAJORITY * len(live)
        passing.append(ok)
        overall = (float(np.mean([m for v in live.values() for m in v]))
                   if live else float("nan"))
        out.append(f"| {value_format.format(arms[arm])} | {len(cleared)} / {len(live)} "
                   f"| {overall:+.1f} | {'**PASS**' if ok else '**FAIL**'} |")
    out.append("")

    best = {}
    for dataset in datasets:
        options = {a: float(np.mean(table[a][dataset]))
                   for a in names if table[a].get(dataset)}
        if options:
            best[dataset] = max(options.items(), key=lambda kv: kv[1])
    out += [f"## Per-dataset best {knob_label} — **not** a result", "",
            "This is what the study would report if the value were chosen after "
            "seeing the score. The gap between it and the table above *is* the "
            "tuning optimism.", "",
            f"| dataset | best {knob_label} | its margin |", "|---|---|---|"]
    for dataset, (arm, value) in sorted(best.items()):
        out.append(f"| {dataset} | {value_format.format(arms[arm])} | {value:+.1f} |")
    if best:
        cherry = float(np.mean([v for _, v in best.values()]))
        honest = max((float(np.mean([m for v in table[a].values() if v for m in v]))
                      for a in names if any(table[a].values())), default=float("nan"))
        out += ["", f"Cherry-picked mean **{cherry:+.1f}** against the best "
                    f"single-value mean **{honest:+.1f}** — a tuning optimism of "
                    f"**{cherry - honest:+.1f}** points.", ""]

    out += ["## Verdict", "",
            (f"**PASS.** At least one pre-named {knob_label} clears +{bar} on a "
             "majority of datasets." if any(passing)
             else f"**FAIL.** No pre-named {knob_label} clears +{bar} on a majority "
                  f"of datasets. {fail_note}"), ""]

    out += ["## Per-seed margins", "",
            "Means above are never reported without these.", ""]
    for arm in names:
        out += [f"**{label(arm)}**", ""]
        for dataset in datasets:
            values = table[arm].get(dataset) or []
            out.append(f"* `{dataset}`: "
                       + (", ".join(f"{x:+.1f}" for x in values) if values else "—"))
        out.append("")
    return "\n".join(out)


def write(path: str, text: str) -> None:
    Path(path).write_text(text)
    print(text)
